apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: petworx
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
