apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: petworx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: petworx-frontend
        image: arielbenichou/petworx-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: VITE_BACKEND_HOST
          value: "http://localhost:8080"
