apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: petworx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5 # Use the official MariaDB image
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: user-password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: mariadb-database
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: mariadb-user
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql # Default path for MariaDB data
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
