apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: petworx
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None # Headless service to allow direct access from the backend
